version: '3.1'

services:
  mysqldb:
    image: mysql:8.0.29
    environment:
       MYSQL_DATABASE: moviedb
       MYSQL_USER: moviedb
       MYSQL_PASSWORD: moviedb
       MYSQL_ROOT_PASSWORD: moviedb
    ports:
        - '3308:3306'
    volumes:
         - ${PWD}/init.db/mysql:/docker-entrypoint-initdb.d