version: '3.1'

services:
  mysqldb:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: sample-db
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: sample-root
    ports:
      - '3308:3306'
    volumes:
      - ${PWD}/init.db/mysql:/docker-entrypoint-initdb.d