version: '3.1'

services:
  postgresdb:
    image: postgres:11
    container_name: postgresdb
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: moviedb
      POSTGRES_PASSWORD: moviedb
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/init.db/postgres:/docker-entrypoint-initdb.d