@base = http://localhost:8080/api 

#### Sign up 
POST {{base}}/auth/signup
Content-Type: application/json

{
    "username": "varun",
    "email": "varun@email.com",
    "password" : "password",
    "role" : ["ROLE_USER"]
}

#### Login 
# @name login 
POST {{base}}/auth/signin
Content-Type: application/json

{
    "username": "varun",
    "password": "password"
}

#### Access All
GET {{base}}/test/all
Content-Type: application/json

#### Access User
GET {{base}}/test/user
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Access Admin
GET {{base}}/test/admin
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json