@base = http://localhost:8080/api 

#### Register
POST {{base}}/auth/signup
Content-Type: application/json

{
  "username": "mani",
  "email": "mani@12345.com",
  "password": "mani12345"
}

#### Login 
# @name login 
POST {{base}}/auth/signin
Content-Type: application/json

{
  "username": "mani",
  "password": "mani12345"
}

#### Get the User
GET {{base}}/auth/me
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Creates a new Movie
# @name movie 
POST {{base}}/movies
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "title": 3333,
  "directedBy": "Cameron",
  "yearOfRelease": 2000,
  "rating": 8.5,
  "genre": "Action",
  "imdbId": "*^&^&^"
}

#### Creates a new Movie
POST {{base}}/movies
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "title": "Superman",
  "directedBy": "Cameron",
  "yearOfRelease": 2000,
  "rating": 8.5,
  "genre": "Action",
  "imdbId": "WWEEWEEW"
}

#### Creates a new Movie
POST {{base}}/movies
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "title": "Superman",
  "directedBy": "Cameron",
  "yearOfRelease": 2000,
  "rating": 8.5,
  "genre": "Action",
  "imdbId": "56565656"
}

#### Get a Movie
GET {{base}}/movies/{{movie.response.body.id}}
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Updates a Movie
PUT {{base}}/movies/{{movie.response.body.id}}
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "title": "spider man",
  "directedBy": "marvel",
  "yearOfRelease": 2021,
  "rating": 8.5,
  "genre": "adventure",
  "imdbId": "spidy"
}

#### List Movies
GET {{base}}/movies
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### List Movies with Page
GET {{base}}/movies?page=0&size=2
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Get a Movie
DELETE {{base}}/movies/{{movie.response.body.id}}
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Get as User
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json