@base = http://localhost:8080/api 

#### Register
POST {{base}}/auth/signup
Content-Type: application/json

{
  "username": "mani",
  "email": "mani@12345.com",
  "password": "mani12345"
}

#### Login 
# @name login 
POST {{base}}/auth/signin
Content-Type: application/json

{
  "username": "mani",
  "password": "mani12345"
}

#### Get the User
GET {{base}}/auth/me
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Get as User
GET {{base}}/test/user
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

#### Get as User
POST {{base}}/auth/logout
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json